import{a as S,S as v,i}from"./assets/vendor-DcHCnVjq.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const P="55702600-e02894471d0a636b9c2f740a2",q="https://pixabay.com/api/";async function f(o,e){return(await S.get(q,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const e=o.map(n=>`
<li class="gallery-item">
<a href="${n.largeImageURL}">
<img src="${n.webformatURL}" alt="${n.tags}" />
</a>
<div class="info">
<p><b>Likes</b><br>${n.likes}</p>
<p><b>Views</b><br>${n.views}</p>
<p><b>Comments</b><br>${n.comments}</p>
<p><b>Downloads</b><br>${n.downloads}</p>
</div>
</li>
`).join("");p.insertAdjacentHTML("beforeend",e),M.refresh()}function B(){p.innerHTML=""}function y(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function L(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}function R(){const o=document.querySelector(".gallery-item");if(!o)return;const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}const w=document.querySelector(".form"),$=document.querySelector(".load-more");let s=1,a="",d=0;w.addEventListener("submit",O);$.addEventListener("click",x);async function O(o){if(o.preventDefault(),a=o.target.elements["search-text"].value.trim(),!!a){s=1,B(),l(),y();try{const e=await f(a,s);if(e.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=Math.ceil(e.totalHits/15),g(e.hits),s<d&&L()}catch(e){i.error({message:"Something went wrong. Please try again!",position:"topRight"}),console.log(e)}finally{b(),w.reset()}}}async function x(){s+=1,l(),y();try{const o=await f(a,s);if(g(o.hits),R(),s>=d){l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}L()}catch(o){i.error({message:"Something went wrong. Please try again!",position:"topRight"}),console.log(o)}finally{b()}}
//# sourceMappingURL=index.js.map
