import{a as S,S as v,i as a}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function u(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const q="55702600-e02894471d0a636b9c2f740a2",M="https://pixabay.com/api/";async function f(r,t){return(await S.get(M,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(o=>`
<li class="gallery-item">
<a href="${o.largeImageURL}">
<img src="${o.webformatURL}" alt="${o.tags}" />
</a>
<div class="info">
<p><b>Likes</b><br>${o.likes}</p>
<p><b>Views</b><br>${o.views}</p>
<p><b>Comments</b><br>${o.comments}</p>
<p><b>Downloads</b><br>${o.downloads}</p>
</div>
</li>
`).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function R(){h.innerHTML=""}function g(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}function L(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}const w=document.querySelector(".form"),B=document.querySelector(".load-more");let s=1,i="",d=0;w.addEventListener("submit",$);B.addEventListener("click",O);async function $(r){if(r.preventDefault(),i=r.target.elements["search-text"].value.trim(),!!i){s=1,R(),l(),g();try{const t=await f(i,s);if(t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=Math.ceil(t.totalHits/15),y(t.hits),s<d?L():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){a.error({message:"Something went wrong. Please try again!",position:"topRight"}),console.log(t)}finally{b(),w.reset()}}}async function O(){s+=1,l(),g();try{const r=await f(i,s);if(y(r.hits),s>=d){l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),L()}catch(r){a.error({message:"Something went wrong. Please try again!",position:"topRight"}),console.log(r)}finally{b()}}
//# sourceMappingURL=index.js.map
